export const LOAD_PROFILE = 'LOAD_PROFILE';

// Portfolio
export const LOAD_PORTFOLIO = 'LOAD_PORTFOLIO';
export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';

export const ADD_NEW_PORTFOLIO = 'ADD_NEW_PORTFOLIO';
export const UPDATE_NEW_PORTFOLIO = 'UPDATE_NEW_PORTFOLIO';
export const DELETE_NEW_PORTFOLIO = 'DELETE_NEW_PORTFOLIO';
