import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/App.scss';
import { Providers } from '@/store/providers';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col items-between min-h-100vh gap-8">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </Providers>
  );
}
